trigger:
- main
pool:
 vmImage: 'ubuntu-latest'

variables:
  build_dir: 'build'
steps:
- task: UsePythonVersion@0
  inputs:
    VersionSpec: '3.x'
- script: |
    sudo apt-get update
    sudo apt-get install -y cmake g++ python3-dev
- script: |
    python -m pip install --upgrade pip
    pip install pybind11 matplotlib
- script: |
    cmake -B $(build_dir) -S
    cmake --build $(build_dir)
- script: |
    pythonw python/test_audio_processing.py

