trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  build_dir: 'build'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    sudo apt-get update
    sudo apt-get install -y cmake g++ python3.10-dev

- script: |
    python -m pip install --upgrade pip
    pip install pybind11 matplotlib numpy scipy

- script: |
    cmake -B $(build_dir) -S . -DPython_EXECUTABLE=$(which python3)
    cmake --build $(build_dir)

- script: |
    python python/test
  displayName: 'Run Unit Tests'
